spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/medicareclinic
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Email configuration (development defaults)
#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=false
#app.mail.from=noreply@medicareclinic.com

